### ISSUE TITLE
cannot import name rdBase

### ISSUE THREAD

**Issue by weiliu620** [GUR9000/KerasNeuralFingerprint#1]
I followed the rdKit instruction and run "sudo apt-get install python-rdkit librdkit1 rdkit-data", and can see the packages are installed no error. And then I got 'cannot import name rdBase' error when run 'python train_finger_print_model'. 

I suspect this is not the fault of this project, but I'll open the issue anyway to track it for everyone.

**Comment by weiliu620** [comment]
And, just curious, it seems this project also include a full copy of rdkit source. What is the rationale of that? Is it because you have a modified version of rdkit? 

But rdkit need to build (at least the rdBase.so need to build). I wonder any instruction for that. For now I just install it using Ubuntu's apt-get. Sometimes got error of no'rdBase' module, sometimes not...

**Comment by GUR9000** [comment]
This problem is indeed unrelated to this project.
What worked well for me was using the Anaconda distribution of python and then [conda install -c https://conda.anaconda.org/rdkit rdkit].
I removed rdkit from the package as it is indeed not helping anyone circumventing these problems.
